# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\0College\0 3rd_2\人工智能\期末pj\welcome.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_welcome(object):
    def setupUi(self, welcome):
        welcome.setObjectName("welcome")
        welcome.resize(730, 531)


        #设置窗口的图标，引用src目录下的花朵.png图片
        self.setWindowIcon(QIcon('./src/花朵.png'))

        self.label = QtWidgets.QLabel(welcome)
        self.label.setGeometry(QtCore.QRect(150, 30, 531, 81))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(welcome)
        self.pushButton.setGeometry(QtCore.QRect(280, 250, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(welcome)
        self.pushButton_2.setGeometry(QtCore.QRect(280, 440, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(welcome)
        self.pushButton_3.setGeometry(QtCore.QRect(280, 340, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(welcome)
        self.pushButton_4.setGeometry(QtCore.QRect(280, 150, 181, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")

        self.retranslateUi(welcome)
        QtCore.QMetaObject.connectSlotsByName(welcome)

    def retranslateUi(self, welcome):
        _translate = QtCore.QCoreApplication.translate
        welcome.setWindowTitle(_translate("welcome", "复旦校园花卉植物鉴别专家系统"))

        self.label.setText(_translate("welcome", "复旦校园花卉植物鉴别专家系统"))
        self.pushButton.setText(_translate("welcome", "普通花卉植物鉴别"))
        self.pushButton_2.setText(_translate("welcome", "退出"))
        self.pushButton_3.setText(_translate("welcome", "编辑规则"))
        self.pushButton_4.setText(_translate("welcome", "专业植物鉴别"))
import img
